---
- name: restart webserver
  service:
    name: "{{ php_webserver_daemon }}"
    state: restarted
  notify: "{{ php_fpm_handler_action }} php-fpm"
  when: php_enable_webserver

- name: restart php-fpm
  service:
    name: "{{ php_fpm_daemon }}"
    state: restarted
  when:
    - php_enable_php_fpm
    - php_fpm_state == 'started'

- name: reload php-fpm
  service:
    name: "{{ php_fpm_daemon }}"
    state: reloaded
  when:
    - php_enable_php_fpm
    - php_fpm_state == 'started'
